# Generated by Django 5.1.7 on 2025-03-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=20)),
                ('temperatura', models.FloatField(max_length=4)),
                ('humedad', models.FloatField(max_length=4)),
            ],
            options={
                'db_table': 'datos',
                'managed': True,
            },
        ),
    ]
