# Generated by Django 5.1.7 on 2025-03-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datos',
            options={},
        ),
        migrations.AlterField(
            model_name='datos',
            name='humedad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='datos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='temperatura',
            field=models.FloatField(),
        ),
    ]
